defaultPortal: the-number-company
portals:
  - name: the-number-company
    portalId: 342177541
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CL6PofiSMxIgQlNQMl8kQEwrAhMACAkCFBwBAgEQAwoBAgMHGygCeAEYhe6UowEgsvf7Jiju6QwyFGjIrnzNN_My-40sTQubCshE2kJhOlhCU1AyXyRATCsCJgAQEwYABgBxACsASAABAAEAAQAIAAEABgACABQABAAYAAQAAQABAAEAAQABAAQAAQAFAAEAEgAJAAMAAQAxAAEAVwAXAAEAQgBUAQEAQhRLNbeiifa4_AhGw2ko9N9HHFz2cEoDbmEzUgBaAGABaLL3-yZwAHgA
        expiresAt: '2025-09-09T15:11:35.922Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTMtOGUyNS05ODVhLTQ3ZmYtYmJkMC03YTk3NjI0ZmMwMDUQhe6UowEYsvf7JioZAAXmkYK1gbIGsHZn1Ngac46QU8YMFwVlf0oDbmEz
